# Joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers
right_thumb_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - right_thumb_joint_palm_to_base
    - right_thumb_joint_base_to_pip
    - right_thumb_joint_pip_to_dip
    - right_thumb_joint_dip_to_fingertip
  gains:
    right_thumb_joint_palm_to_base: {p: 100, i: 1, d: 0.001}
    right_thumb_joint_base_to_pip: {p: 100, i: 1, d: 0.001}
    right_thumb_joint_pip_to_dip: {p: 100, i: 1, d: 0.001}
    right_thumb_joint_dip_to_fingertip: {p: 100, i: 1, d: 0.001}
