controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoul_base2shoul_joint
      - right_shoul2shoul_rot_joint
      - right_arm2armrot_joint
      - right_armrot2elbow_joint
      - right_forearm2forearmrot_joint
      - right_forearmrot2forearm_pitch_joint
      - right_forearm_pitch2forearm_roll_joint
initial:  # Define initial robot poses per group
  - group: right_arm
    pose: home