right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_shoul_base2shoul_joint
    - right_shoul2shoul_rot_joint
    - right_arm2armrot_joint
    - right_armrot2elbow_joint
    - right_forearm2forearmrot_joint
    - right_forearmrot2forearm_pitch_joint
    - right_forearm_pitch2forearm_roll_joint
  gains:
    right_shoul_base2shoul_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoul2shoul_rot_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm2armrot_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_armrot2elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_forearm2forearmrot_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_forearmrot2forearm_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_forearm_pitch2forearm_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1