controller_list:
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_shoul_base2shoul_joint
      - right_shoul2shoul_rot_joint
      - right_arm2armrot_joint
      - right_armrot2elbow_joint
      - right_forearm2forearmrot_joint
      - right_forearmrot2forearm_pitch_joint
      - right_forearm_pitch2forearm_roll_joint